### ISSUE TITLE
Issue with AutoFlushSendQueue

### ISSUE THREAD

**Issue by ItalyToast** [lidgren/lidgren-network-gen3#1]
When AutoFlushSendQueue is enabled: heartbeat() enumerates all channels on all connections and causes a lot of trashing causing problems if a peer have more than ~60 connections

**Comment by lidgren** [comment]
Commit d57f7045fe4606ba19fb45f13fec87a0127bac70 adds a flag per peer that is raised by the sender channels; if no message is queued the flag will be false and the channels will not be traversed.

**Comment by ItalyToast** [comment]
That improved it a lot! thank you :D
