### ISSUE TITLE
Can I make a 1vs1 game with lidgren library ?

### ISSUE THREAD

**Issue by comDeven** [lidgren/lidgren-network-gen3#101]
I can make multiplayer game but I need multi 1vs1 games :)
Like chess for example

**Comment by Kaladrius2trip** [comment]
Yes you may. But you might need write some mechanism for control of game's rooms with parameters something like "maximum players per room".

**Comment by dendriel** [comment]
Hello,

you may set the MaximumConnections configuration if using a server; or enable de ConnectionApproval event to accept/deny connection requests accordingly to some rule.

Check NetPeerConfiguration.cs for more info about this settings.

Regards,
