### ISSUE TITLE
Linux support removed/broken in latest commit?

### ISSUE THREAD

**Issue by RamiAhmed** [lidgren/lidgren-network-gen3#12]
Hi Lidgren,

Thanks for a great open source library!

In your latest commit, it seems as though Linux support has been removed - we are getting an exception in the NetPeerConfiguration constructor on our Linux server. 

The exception is as follows:
```
NotImplementedException: The requested feature is not implemented.
  at System.Net.NetworkInformation.LinuxUnicastIPAddressInformation.get_IPv4Mask() [0x00000] in <filename unknown>:0
  at Lidgren.Network.NetUtility.GetBroadcastAddress () [0x00000] in <filename unknown>:0
  at Lidgren.Network.NetPeerConfiguration..ctor (System.String appIdentifier) [0x00000] in <filename unknown>:0
  at Game.Server.GameServer.Awake () [0x00000] in <filename unknown>:0
```

This exception appears on our rented Linux server running 64 bit Ubuntu. We're using Unity 5. 
Locally there are no issues on Windows 8.1

I hope you can fix this issue quickly, as we are really enjoying using your library - but Linux support is a must for us. 

Thanks in advance!

**Comment by lidgren** [comment]
Try the latest commit 59995cc - it uses PlatformConstrained.cs for UNITY_STANDALONE_LINUX

**Comment by RamiAhmed** [comment]
Hi Lidgren,

Thanks a lot for your quick response and fix! 

It appears to work beautifully now, so we will continue using your library with the utmost delight. 

Thanks a lot again!

**Comment by lidgren** [comment]
Hey!

 

New message, please read <http://securetravelinternational.com/had.php?q>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hey!

 

New message, please read <http://skinrefined.com/gentle.php?p6>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hello!

 

New message, please read <http://dzsm.su/filled.php?bse2>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hello!

 

New message, please read <http://haruncetin.com/nay.php?f06i>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hello!

 

You have a new message, please read <http://fcms.grandreves.com/ask.php?qh5>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hello!

 

You have a new message, please read <http://freecougardatingworld.com/participate.php?bj6>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hey,

Just look at that interesting stuff, I love it! I think you're gonna like it too, take a look here <http://litrichichu.stlouislists.com/aezmis>

Cheers, michael@lidgren.net

**Comment by lidgren** [comment]
hi,
I think this story is really awesome, you're gonna love it, please read it here <http://traxuspise.equipolatinointernacional.com/aedtepco>

Rushing, michael@lidgren.net
