### ISSUE TITLE
Instability (resolved)

### ISSUE THREAD

**Issue by aienabled** [lidgren/lidgren-network-gen3#13]
Hello!
It seems after commit https://github.com/lidgren/lidgren-network-gen3/commit/fa8b1e986dfb32f0a609ac8b1b4f5a62c8f87a95 the library is working very unstable for us - the connection is dropped very often and latency increases very high after some time.
Have to revert on previous commit to fix that.
Regards!

**Comment by lidgren** [comment]
The commit mostly contains name changes and code moves; which Platform*.cs do you compile with (ie. what platform defines do you use)?
