### ISSUE TITLE
License and Nuget package

### ISSUE THREAD

**Issue by Kittyfisto** [lidgren/lidgren-network-gen3#14]
Hi there,

since I'm unable to find a license file, am I correct to assume that it is still being published under the MIT license like the google code repo? If so, could you add this to your repo to clear further confusion (or point me right to it because I was blind), please?

Another quick question: Would you mind to create a nuget package for this repository as well? I plan on using your library and it would make my job easier ;)

Thanks
Kittyfisto

**Comment by adeadrat** [comment]
I second this, a license would be nice. The project hosted at google code is MIT. Is it still MIT?

**Comment by lidgren** [comment]
https://www.nuget.org/packages/Lidgren.Network/1.0.2
