### ISSUE TITLE
Lidgren built with mono fails on Linux

### ISSUE THREAD

**Issue by RamiAhmed** [lidgren/lidgren-network-gen3#16]
Hi Lidgren,

We're encountering an issue in the startup of a server with the newest version of Lidgren here from Github. The file is built with mono and is therefore an .exe file, but it is supposed to run on a Linux platform (we know this worked before).

It appears now, probably due to the recent updates, that GetBroadcastAddress is attempting to call a Linux specific method implementation, which does not exist in Mono where it should probably be using the Windows equivalent. At least that is my guess.

The error message is as follows:
```
Unhandled Exception: System.NotImplementedException: The requested feature is not implemented.
 at System.Net.NetworkInformation.LinuxUnicastIPAddressInformation.get_IPv4Mask () [0x00000] in <filename unknown>:0
  at Lidgren.Network.NetUtility.GetBroadcastAddress () [0x00000] in <filename unknown>:0
  at Lidgren.Network.NetPeerConfiguration..ctor (System.String appIdentifier) [0x00000] in <filename unknown>:0
  at Lobby.Server.LobbyServer..ctor () [0x00000] in <filename unknown>:0
  at Lobby.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: The requested feature is not implemented.
  at System.Net.NetworkInformation.LinuxUnicastIPAddressInformation.get_IPv4Mask () [0x00000] in <filename unknown>:0
  at Lidgren.Network.NetUtility.GetBroadcastAddress () [0x00000] in <filename unknown>:0
  at Lidgren.Network.NetPeerConfiguration..ctor (System.String appIdentifier) [0x00000] in <filename unknown>:0
  at Lobby.Server.LobbyServer..ctor () [0x00000] in <filename unknown>:0
  at Lobby.Server.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
```

Hoping that a speedy solution can be found so we may continue using your excellent library.

Thanks in advance.

**Comment by RamiAhmed** [comment]
bump

We could really use a solution for this.

**Comment by lidgren** [comment]
Which Platform*.cs are you compiling with?

**Comment by RamiAhmed** [comment]
Hey Lidgren,

Thanks for your response!

Since we're developing in Unity5, and deploying on a Linux server, I'm assuming that the PlatformConstrained is used - although I'm not actually sure? 

However, as I mentioned in the OP, my assumption is that it is indeed using this PlatformConstrained which seeks to call Linux-specific methods - but Mono does not support this (as it is likely expecting Windows-based methods). However, I'm not sure of this either, it's just my guess.

**Comment by lidgren** [comment]
Verify which platform you're using to compile. If you're using PlatformConstrainted it's failing on "return IPAddress.Broadcast"... try replacing with "return IPAddress.Parse("255.255.255.255");" instead.

**Comment by RamiAhmed** [comment]
Hi Lidgren,

I'm sorry for my confusion earlier. We are compiling with 'PlatformWin32.cs' with Mono and attempting to run a built executable (.exe) file on a Linux Ubuntu server (no Unity involved) - of course using mono on the server as well to execute the file. We know this worked earlier (prior to the last month's commits).

Therefore, even though I tried your suggestion, it had no effect.

**Comment by R4stl1n** [comment]
I found it easier to build with VS for 3.5 and bring that into my mono environment.

**Comment by Cyral** [comment]
Compiling with __CONSTRAINED__ fixes this error on mono for me.

**Comment by Nrezinorn** [comment]
I am getting the same Error on both OS X and Linux (Centos7)  using `xbuild /tv:4.0  MasterServerSample.sln`
@Cyral :  i don't understand your fix using "__CONSTRAINED__".  Can you explain further?  Thanks everyone!

**Comment by Scellow** [comment]
Same here, compiling with ```__CONSTRAINED__``` fixed the issue

@Nrezinorn 

Right click on your project -> Option -> Compiler

And add ```__CONSTRAINED__```  in Define Symbols

![Screenshot]
(http://i.imgur.com/dqgwLA1.png)
