### ISSUE TITLE
Will lidgren combine small messages to one UDP packet?

### ISSUE THREAD

**Issue by heroboy** [lidgren/lidgren-network-gen3#37]

**Comment by MichaelDePiazzi** [comment]
Yes, but the time for coalescing messages is very short (I think @lidgren mentioned that it was about 3 heartbeats, which is very fast). But generally if you send all of the messages at the same time, then they will be combined into 1 packet (assuming it doesn't exceed the MTU size and fragment the packet). I am doing this, and it seems to work well for me. You can check how many packets are actually being sent by looking at the connections "Statistics.SentPackets" property.

**Comment by lidgren** [comment]
That is correct.
