### ISSUE TITLE
Please delete unused NetAESEncryption, it can't be compiled in Unity3d.

### ISSUE THREAD

**Issue by heroboy** [lidgren/lidgren-network-gen3#38]

**Comment by lidgren** [comment]
I need more details; why does it not compile, on what platform does it not compile?

**Comment by heroboy** [comment]
Because `AesCryptoServiceProvider` is not avaliable in Unity.
See https://github.com/lidgren/lidgren-network-gen3/commit/f2e70ecd5d546c82f41c301fc941f51a7f712a0a
You deleted the workaround.

**Comment by AgentFire** [comment]
It **is** available for me.

**Comment by forestrf** [comment]
Check [how to use this library with Unity3D](../wiki/Unity3D), it might help
