### ISSUE TITLE
NetConnection.m_sentPingTime

### ISSUE THREAD

**Issue by forestrf** [lidgren/lidgren-network-gen3#60]
In the class NetConnection, the variable m_sentPingTime receives a value at InitializePing() that SendPing() overwritten a little after without being readed.

What was the intention of this lines?
```C#
// randomize ping sent time (0.25 - 1.0 x ping interval)
m_sentPingTime = now;
m_sentPingTime -= (m_peerConfiguration.PingInterval * 0.25f); // delay ping for a little while
m_sentPingTime -= (MWCRandom.Instance.NextSingle() * (m_peerConfiguration.PingInterval * 0.75f));
```
Thank you

**Comment by lidgren** [comment]
You are correct. Removed in latest commit.
