### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by doodlemeat** [lidgren/lidgren-network-gen3#80]
Is this project dead?

**Comment by forestrf** [comment]
More like email hacked

**Comment by doodlemeat** [comment]
What u mean?

**Comment by forestrf** [comment]
This: https://github.com/lidgren/lidgren-network-gen3/pull/4#issuecomment-237390222

**Comment by lidgren** [comment]
Something stole my entire Contacts list and github helpfully has reply-to which contain authentication - so they're just sending mails to random contacts of mine - some ending up here :-(
