### ISSUE TITLE
Library starts lagging at 300Mbytes/sec

### ISSUE THREAD

**Issue by MvanDoorn** [lidgren/lidgren-network-gen3#98]
Hi Lidgren, we have a setup over a local network between 2 computers with both a 25Gbit network adapter. While benchmarking this setup I'm able to reach a speed close to 3 GBytes/sec. I would like to do the same with the use of your library to send a large load of data. With some tweaking of the NetConstants I'm now able to reach 300 Mbytes/sec max. When I try to send more data it seems like the library can't handle it anymore since it start building up a queue on the sending side.

I'm testing with send mode ReliableOrdered and ReliableSequenced. I have increased the DefaultWindowSize from 64 to 512. Without changing the DefaultWindowSize, the delay started to occure at around 80 MBytes/sec. 

Can you tell me if it's possible to reach a higher throughput with your library? If so, what values do I need to change to reach a throughput of around 3GBytes/sec?

Your help is much appreciated!

**Comment by lidgren** [comment]
It will be difficult. The library isn't currently built to achieve high bandwidth; it's focused on low latency, easy set up. I would advice using TCP for this type of data transfer.

**Comment by MvanDoorn** [comment]
I disagree with using TCP for our solution. The latency of TCP is way to high for our solution. We are trying to send lots of 4K raw data video streams that need to be real-time. Thanks for your reply anyway!
